### ISSUE TITLE
Update package requirements

### ISSUE THREAD

**Issue by KayKursawe** [secuconnect/secuconnect-php-sdk#28]
Requirements psr/cache and psr/log should be updated to version ^3.
Atm, these outdated requirements are blocking me when trying to update my Symfony app.

**Comment by r-simlinger** [comment]
@KayKursawe should be solved with the release 2.30.0 today:
https://github.com/secuconnect/secuconnect-php-sdk/releases/tag/2.30.0

**Comment by KayKursawe** [comment]
Seems to work, thanks a lot.
:+1:
