### ISSUE TITLE
Parsing error in PaymentTransactionCancelDTO.php

### ISSUE THREAD

**Issue by sgregor** [secuconnect/secuconnect-php-sdk#45]
https://github.com/secuconnect/secuconnect-php-sdk/blob/8c85937eb5cec16f8c3990c8f8f2c0a5bc11aae4/lib/Model/PaymentTransactionCancelDTO.php#L43

This line gives a parsing error. The single quote should be escaped.

**Comment by r-simlinger** [comment]
thanks for reporting, solved in #46 #
